# Generated by Django 5.1.3 on 2024-11-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('detail', models.TextField(max_length=200)),
                ('valor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('moto_marca', models.CharField(max_length=15)),
                ('serie', models.CharField(max_length=15)),
                ('placa', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
