# Generated by Django 5.1.3 on 2024-11-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_plato_nombre_restaurant_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_restaurant',
            field=models.CharField(max_length=55),
        ),
    ]
