# Generated by Django 5.1.3 on 2024-12-07 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_plato_imagen_plato_restaurante_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicio.plato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
