# Generated by Django 5.1.3 on 2024-12-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_cliente_plato_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(help_text='Ingrese su apellido', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(help_text='ingrese la direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre:', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Telefono:', max_length=10),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='direccion',
            field=models.CharField(help_text='ingrese la direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre:', max_length=50),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='telefono',
            field=models.CharField(help_text='Telefono:', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='direccion',
            field=models.CharField(help_text='ingrese la direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre:', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='telefono',
            field=models.CharField(help_text='Telefono:', max_length=10),
        ),
    ]
