# Generated by Django 5.1.3 on 2024-12-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_cliente_apellido_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='detail',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='plato',
            old_name='name',
            new_name='nombre_plato',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='clave',
        ),
    ]
