# Generated by Django 5.1.3 on 2024-12-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_rename_detail_plato_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
