# Generated by Django 5.1.3 on 2024-12-08 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_repartidor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='restaurantes',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='servicio.restaurante'),
        ),
    ]
